async function api(url, options = {}) {
  const r = await fetch(url, {headers:{"Content-Type":"application/json"}, ...options});
  return r.json();
}
const LABELS={waiting:"WAITING",running:"RUNNING",retrying:"RETRYING",paused:"PAUSED",pausing:"PAUSING",cancelling:"CANCELLING",failed:"FAILED",completed:"COMPLETED",cancelled:"CANCELLED"};
const logCursors={};
let conversationId=localStorage.getItem("jarvisConversationId")||null;
async function health(){const x=await api("/api/health");document.getElementById("health").textContent=x.status==="ok"?`ONLINE · WORKER ${String(x.worker||"unknown").toUpperCase()}`:"OFFLINE";renderMigration(x.memory_migration||{});}
async function createAndRun(){const goal=document.getElementById("goal").value.trim();if(!goal)return;await api("/api/tasks",{method:"POST",body:JSON.stringify({goal})});document.getElementById("goal").value="";loadTasks();}
async function runTask(id){await api(`/api/tasks/${id}/run`,{method:"POST"});loadTasks();} async function pauseTask(id){await api(`/api/tasks/${id}/pause`,{method:"POST"});loadTasks();} async function resumeTask(id){await api(`/api/tasks/${id}/resume`,{method:"POST"});loadTasks();} async function cancelTask(id){await api(`/api/tasks/${id}/cancel`,{method:"POST"});loadTasks();}
async function loadLogs(id){const after=logCursors[id]||0,d=await api(`/api/tasks/${id}/logs?after_id=${after}&limit=500`),target=document.getElementById(`logs-${id}`);if(!target)return;for(const log of d.logs||[]){const line=document.createElement("div");line.className=`log log-${esc(log.level)}`;line.innerHTML=`<span class="log-time">${esc(new Date(log.created_at).toLocaleTimeString())}</span><span class="log-level">${esc(log.level.toUpperCase())}</span><span>${esc(log.message)}</span>`;target.appendChild(line);logCursors[id]=Math.max(logCursors[id]||0,Number(log.id));}target.scrollTop=target.scrollHeight;}
function controlsFor(t){if(t.status==="waiting"||t.status==="retrying"||t.status==="running")return `<button class="pause" onclick="pauseTask('${t.id}')">Pause</button><button class="danger" onclick="cancelTask('${t.id}')">Cancel</button>`;if(t.status==="paused")return `<button class="run" onclick="resumeTask('${t.id}')">Resume</button><button class="danger" onclick="cancelTask('${t.id}')">Cancel</button>`;if(t.status==="failed"||t.status==="cancelled")return `<button class="run" onclick="runTask('${t.id}')">Queue again</button>`;return "";}
async function loadTasks(){const tasks=await api("/api/tasks"),box=document.getElementById("tasks");if(!tasks.length){box.innerHTML='<p class="muted">No tasks yet.</p>';return;}box.innerHTML=tasks.map(t=>`<article class="task"><div class="task-top"><div class="status status-${esc(t.status)}">${esc(LABELS[t.status]||t.status)}</div><div class="actions">${t.retry_count?`<span class="muted">retry ${esc(t.retry_count)}</span>`:""}${controlsFor(t)}</div></div><div class="goal">${esc(t.goal)}</div>${t.result?`<div class="step passed">${esc(t.result)}</div>`:""}${t.error?`<div class="error">${esc(t.error)}</div>`:""}<div class="muted">Updated ${esc(t.updated_at||"")}</div><details open><summary>Live task log</summary><div id="logs-${t.id}" class="logs"></div></details><div id="steps-${t.id}" class="muted">Loading steps…</div></article>`).join("");for(const t of tasks){await loadLogs(t.id);const d=await api(`/api/tasks/${t.id}`),s=d.steps||[],target=document.getElementById(`steps-${t.id}`);if(target)target.innerHTML=s.length?s.map(x=>`<div class="step"><b>${esc(x.status)}</b> — ${esc(x.description)}<br><span class="muted">${esc((x.critique||"").slice(0,400))}</span></div>`).join(""):"No execution steps yet.";}}
async function newConversation(){const d=await api("/api/conversations",{method:"POST"});conversationId=d.conversation_id;localStorage.setItem("jarvisConversationId",conversationId);document.getElementById("chat").innerHTML="";}
async function sendMessage(){const input=document.getElementById("memoryQuery"),content=input.value.trim();if(!content)return;if(!conversationId)await newConversation();appendChat("user",content);input.value="";const d=await api(`/api/conversations/${conversationId}/messages`,{method:"POST",body:JSON.stringify({content})});appendChat("assistant",d.answer||"");}
function appendChat(role,text){const box=document.getElementById("chat"),el=document.createElement("div");el.className=`chat-message ${role}`;el.textContent=text;box.appendChild(el);box.scrollTop=box.scrollHeight;}
async function loadConversation(){if(!conversationId)return;const d=await api(`/api/conversations/${conversationId}`);document.getElementById("chat").innerHTML="";(d.messages||[]).forEach(m=>appendChat(m.role,m.content));}
async function searchMemory(){const q=document.getElementById("search").value.trim();if(!q)return;const d=await api(`/api/memory/search?q=${encodeURIComponent(q)}&limit=20`);document.getElementById("memoryResults").innerHTML=(d.memories||[]).map(m=>`<div class="memory-item"><b>${esc(m.kind)} · ${esc(m.key)}</b><span>${esc(m.content)}</span><small>${esc(m.scope)} · confidence ${Number(m.confidence).toFixed(2)}</small></div>`).join("")||'<div class="muted">No matching memories.</div>';}
async function extractWorkspace(){await api("/api/memory/workspace/extract",{method:"POST"});searchMemory();}
async function startMigration(){setMigrationBusy(true);const d=await api("/api/memory/embeddings/migrate",{method:"POST"});renderMigration(d);setMigrationBusy(false);}
async function resumeMigration(){await startMigration();}
async function stopMigration(){setMigrationBusy(true);const d=await api("/api/memory/embeddings/migrate/stop",{method:"POST"});renderMigration(d);setMigrationBusy(false);}
function setMigrationBusy(busy){["migrationStart","migrationResume","migrationStop"].forEach(id=>{const el=document.getElementById(id);if(el)el.disabled=busy;});}
function renderMigration(m){const status=String(m.status||"idle").toLowerCase(),total=Number(m.total||0),processed=Number(m.processed||0),percent=Number(m.percent??(total?processed/total*100:0));document.getElementById("migrationStatus").textContent=status.toUpperCase();document.getElementById("migrationStatus").className=`status migration-status-${esc(status)}`;document.getElementById("migrationBar").style.width=`${Math.max(0,Math.min(100,percent))}%`;document.getElementById("migrationPercent").textContent=`${percent.toFixed(1)}%`;document.getElementById("migrationTotal").textContent=total;document.getElementById("migrationEmbedded").textContent=Number(m.embedded||0);document.getElementById("migrationSkipped").textContent=Number(m.skipped||0);document.getElementById("migrationFailed").textContent=Number(m.failed||0);document.getElementById("migrationRemaining").textContent=Number(m.remaining??Math.max(0,total-processed));document.getElementById("migrationSummary").textContent=total?`${processed} of ${total} memories processed`:`${status==='idle'?'No migration has run yet.':status}`;const err=document.getElementById("migrationError");if(m.last_error){err.hidden=false;err.innerHTML=`<b>Latest failure</b><div>${esc(m.last_error)}</div>`;}else{err.hidden=true;err.textContent="";}document.getElementById("migrationUpdated").textContent=m.updated_at?`Last updated ${new Date(m.updated_at).toLocaleString()}`:"";const active=["running","starting"].includes(status),resumable=["stopped","failed"].includes(status);document.getElementById("migrationStart").hidden=active||resumable;document.getElementById("migrationResume").hidden=!resumable;document.getElementById("migrationStop").hidden=!active;}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));}
health();loadTasks();loadConversation();setInterval(()=>{health();loadTasks();},2000);
